# EmbedFile.cmake - Embeds a file as a C++ byte array
# Usage: cmake -DINPUT_FILE=<file> -DOUTPUT_FILE=<file> -P EmbedFile.cmake

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE and OUTPUT_FILE must be defined")
endif()

file(READ "${INPUT_FILE}" content HEX)
string(LENGTH "${content}" content_length)

# Start building the output header
set(output "// Auto-generated from ${INPUT_FILE}\n")
set(output "${output}// Do not edit this file manually\n\n")
set(output "${output}namespace vuk::embedded {\n\n")
set(output "${output}constexpr unsigned char html_template_data[] = {\n")

# Convert hex string to array of bytes
set(counter 0)
set(bytes_per_line 16)
while(counter LESS content_length)
    string(SUBSTRING "${content}" ${counter} 2 byte)
    set(output "${output}0x${byte},")
    
    math(EXPR counter "${counter} + 2")
    math(EXPR line_pos "${counter} / 2 % ${bytes_per_line}")
    
    if(line_pos EQUAL 0 AND counter LESS content_length)
        set(output "${output}\n")
    endif()
endwhile()

set(output "${output}\n};\n\n")
set(output "${output}constexpr size_t html_template_size = sizeof(html_template_data);\n\n")
set(output "${output}} // namespace vuk::embedded\n")

file(WRITE "${OUTPUT_FILE}" "${output}")
message(STATUS "Embedded ${INPUT_FILE} -> ${OUTPUT_FILE} (${content_length} bytes)")
